package com.studyforread.server.api;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    CONFLICT,
    RATE_LIMITED,
    INTERNAL_ERROR,
    AUTH_EMAIL_ALREADY_EXISTS,
    AUTH_INVALID_CREDENTIALS,
    AUTH_TOKEN_EXPIRED,
    AUTH_REFRESH_TOKEN_INVALID,
    BOOK_METADATA_INVALID,
    BOOK_PROGRESS_INVALID,
    LEXEME_NOT_FOUND,
    WORD_CARD_ALREADY_EXISTS,
    WORD_CARD_NOT_FOUND,
    PRIVATE_CARD_INVALID,
    TRANSLATION_PROVIDER_UNAVAILABLE,
    TRANSLATION_TEXT_TOO_LONG,
    TRANSLATION_UNSUPPORTED_LANGUAGE_PAIR,
    ADMIN_INVALID_CREDENTIALS,
    ADMIN_REQUIRED,
    ADMIN_DISABLED,
    ADMIN_LEXEME_INVALID,
    ADMIN_LEXEME_DUPLICATE
}
